name: 'Get & cache dependencies'
description: 'Get dependencies and cache them for future runs'
inputs:
  caching: 
    description: 'Whether to cache dependencies or not'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
      - name: Cache dependencies
        if: ${{ inputs.caching == 'true' }}
        run: npm ci
        shell: bash